### ISSUE TITLE
Addon's 'init` is called when the settings are view

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1017]
### Expected behaviour
I can load the Addon settings page w/o the init being called

### Actual behaviour
Init is called, and in my case because I needed a setting for the init to succeed, it caused an error

### Steps to reproduce
1. Make a listener w/ an `init` that needs a config setting 
2. Load the addon settings page

**Comment by edalzell** [comment]
Just remembered why I do it that way...if you don't use the init, you have to initialize in every entry point in your Listener, instead of just one spot.

**Comment by jasonvarga** [comment]
The listener gets new'ed up when we register events. So, every request. Just because you're able to put stuff in `init()`, doesn't always mean you should.

Instead of this:

```
private $thing;

public function init()
{
    $this->thing = new Thing;
}

public function something()
{
    $this->thing->something();
}
```

Maybe consider this:

```
private $thing;

public function something()
{
    $this->thing()->something();
}

private function thing()
{
    if ($this->thing) {
        return $this->thing;
    }

    return $this->thing = new Thing;
}
```

Or even just

```
public function something()
{
    $thing = new Thing;

    $thing->something();
}
```

You sent me your addon this issue is referring to.
You're only ever using `Thing` in one method: `something`. The third snippet is probably good enough.

**Comment by edalzell** [comment]
OK, that makes sense.

I'll go see if I can add to the addon docs so others don't run into this.
