### ISSUE TITLE
Resource not found when slug is resources

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1025]
### Expected behaviour

Page should display as normal
### Actual behaviour

`Resource not found` was shown instead.
### Steps to reproduce
1.  Make page with the slug "resources"
2. Navigate to that page.
3. Error shows
### Server configuration

**Operating system**: Valet
Valet

**Web server:**
OSX Sierra
**PHP version:**
Valet latest
**Statamic version:**
2.1.14
**Updated from an older Statamic or fresh install:**
Updated
**List of installed addons:**
None

I can't duplicate on a different install. It may be related to me upgrading from 2.1.10 at one time???
Making the slug "resource" displays the page normally.

**Comment by jasonvarga** [comment]
In index.php change the value of $resources

On Sun, Oct 09, 2016 at 5:44 PM Sheldon Kotyk

<
mailto:Sheldon Kotyk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Expected behaviour

Page should display as normal

Actual behaviour

Resource not found

was shown instead.

Steps to reproduce

Make page with the slug "resources"

Navigate to that page.

Error shows

Server configuration

Operating system

: Valet

Valet

Web server:

OSX Sierra

PHP version:

Valet latest

Statamic version:

2.1.14

Updated from an older Statamic or fresh install:

Updated

List of installed addons:

None

I can't duplicate on a different install. It may be related to me upgrading from 2.1.10 at one time???

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/statamic/v2-hub/issues/1025
, or

**Comment by sheldonkotyk** [comment]
Yup. Thanks.

**Comment by anthubbard** [comment]
@jasonvarga this just happened to me on 2.7.1?

**Comment by sheldonkotyk** [comment]
@anthubbard make sure 
```$resources = '_resources';```
in index.php

**Comment by anthubbard** [comment]
Thank you. I was more commenting cause I assumed it should have been fixed...?

**Comment by sheldonkotyk** [comment]
I haven't downloaded a fresh copy of statamic in a while but I *think* the download has the underscore now.
