### ISSUE TITLE
FR: Option for "whoops" errors to clear the cache

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1126]
Since the vast majority of errors appear to be fixed by clearing the cache, and options to have "whoops" errors that crash the site automatically clear the cache would make the site a lot more resilient and self-healing.

**Comment by sg-modlab** [comment]
I just got a whoops on one of our sites that a cache clear fixed. This seems likes a good feature request.

**Comment by jeremydouglas** [comment]
This hasn't been too much of a problem for me lately, but for a recent band-aid solution, @jasonvarga and I came up with this:

[https://gist.github.com/jeremydouglas/c58ca38a379e4cc1563bb674e8759080](https://gist.github.com/jeremydouglas/c58ca38a379e4cc1563bb674e8759080)

The Addon is his, the crude .js is mine. 

I built this because I have a site with a large Workshop edit form, using js to autosave. It's hard for me and the Statamic tech support to pin down exactly why the site randomly 404s every few days. It seems to be related to the form somehow. To keep things running for my client, I have the above installed.
