### ISSUE TITLE
Control Panel: User Search field (on /cp/users) does no work in 2.5.1t

### ISSUE THREAD

**Issue by markzegarelli** [statamic/v2-hub#1209]
### Expected behaviour
On 2.1.18, the User Search field filtered the list of users in the table based on name, email, or user name.

### Actual behaviour
On 2.5.1, this field no longer works

### Steps to reproduce
1.  Go to` /cp/users`
2.  Enter the first name of an existing user
3.  

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
nginx
**PHP version:**
7.1
**Statamic version:**
2.5.1
**Updated from an older Statamic or fresh install:**
Updated from 2.5

**Comment by danieljwestman** [comment]
Same here, where frustrating!

No error in logs... 

Statamic 2.5.1 on PHP 7.0

**Comment by jackmcdade** [comment]
The table search is actually disabled for now, we missed removing it from the user section. When we added pagination, it killed the search method we're using. We're gonna need a little time to rework it as an ajax call instead of table filter. Just a heads up, the next patch will remove the search box entirely, and then it'll come back with new powers at a later (but hopefully not too much later) one.

**Comment by danieljwestman** [comment]
Oh 2bad, the search is an important feature. Hope it will come back soon!

**Comment by jackmcdade** [comment]
I hear ya! The global search still works, albeit not quite as narrowly focused.
