### ISSUE TITLE
Partial broken after upgrade 2.5.2

### ISSUE THREAD

**Issue by marconucara** [statamic/v2-hub#1246]
### Expected behaviour
If I create a fieldset "A" and I use it as a partial in fieldsets "B" and "C", this fieldsets should refers the original partial "A" and when I change or add fields to "A", i should see that fields in "B" and "C" data-entry page without any change at "B", "C" fieldsets yaml.

### Actual behaviour
If open an **old fieldset**  "B" that refers "A" as partial I see all "A" fields exploded (it is like if I added all "A" fields at "B"). If i save I see all "A" fields copied in "B" (in "B" yaml file). Now if I change "A" it is just a copy and "B" fieldset remain the same.

***old fieldset** because created before upgrade

If I try to create a new field that use a partial I can't neither to choose a fieldset that is flegged as `hide: true` as I used every partial (other bug? same bug? just as expected?). Than I've the same bugged behaviour anyway.

### Steps to reproduce
As explained before.

### Server configuration
**Operating system**: 
dev: OSX
pre-prod: amazon linux

**Web server:**
dev: valet
pre-prod: apache 2.4

**PHP version:**
dev: 7.0.14
pre-prod: 7.0.14

**Statamic version:**
2.5.2

**Updated from an older Statamic or fresh install:**
direct upgrade from 2.1.19

**List of installed addons:**
 - [Placid](https://github.com/alecritson/Placid-Statamic)

**Comment by rrelmy** [comment]
@jasonvarga This bug is pretty easy to fix.

The ajax parameters  passed to `/get?partials=false&creating...` are evaluated as string. And we know `"false" == true`


Changing line 106 inside `FieldsetController.php` fixes this particular problem, but I think the `creating` parameter is affected too.
``` php
    $array = $fieldset->toArray(bool($this->request->input('partials', true)));
```

**Comment by lukeagsmith** [comment]
I've bumped into this too:

1. Selecting a partial in the fieldset editor in the CP adds the fields of the partial to the fieldset yaml you are editing rather than linking them with a partial fieldtype.

2. You can't select hidden fieldsets from the list of partials in the dropdown. I would imagine most people have `hide: true` in their partial fieldsets.

**Comment by marconucara** [comment]
Nothing solved after 2.5.4 update

**Comment by JayVerb** [comment]
This is causing much headache, especially trying to add a meta partial to all fieldsets. I have other common partials that I'm holding off on adding, hoping this gets resolved soon.

**Comment by lukeagsmith** [comment]
@JayVerb partials will still work as they should if you add them in the `yaml` instead of the control panel, so could get your meta partial added in if it's holding you up.

**Comment by JayVerb** [comment]
@lukeagsmith Yes, I'm still building out the fieldsets for the site so if I alter any of them, the partial then loads the structure into the `yaml`. Nothing really holding me up, but thanks!
