### ISSUE TITLE
Email templates don't get split into text and html with CRLF line endings.

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1274]

**Comment by rrelmy** [comment]
Frontmatters in templates and partials do not work either if CRLF line endings are used ;-)

**Comment by jackmcdade** [comment]
Correct!

**Comment by jackmcdade** [comment]
Squashed for next release.

**Comment by rrelmy** [comment]
Thanks for some windows care.

But right no I have more trouble developing on windows 😢 
I used to checkout files with as-is and commit them with `LF` but now this wont work anymore because I am forced to use `CRLF` on windows. _Yes, I hate `CRLF` as much as you do_.
I hope the most web developers are forcing `LF` in their editors :-)

Would it be possible to support both `LF` and `CRLF` while parsing templates?
