### ISSUE TITLE
Can't use Template fieldtype AND send email via API

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1318]
### Expected behaviour
Should be able to use Template fieldtype to set users pick a template AND use the `Email` class to send that email.

### Actual behaviour
The Email class hard-codes the template path, presuming `templates\email`, however the Template fieldtype stores the full path to the template, i.e. `email\foo.html`. This means the code looks for the template in `email\email\foo.html`

### Steps to reproduce
1. Put a Template fieldtype in your addon settings 
2. Pick a template in a folder
3.  Use the API to send an email using that config

### Server configuration
**Statamic version:**
2.5.5

**Comment by jasonvarga** [comment]
Can't you just trim out the `email` bit? Just make sure people put their email templates where they are supposed to go.

**Comment by edalzell** [comment]
I *could* but that forces them to put the templates in a specific spot, which I'd rather not do.

I have another hack, prepend the path with `../` so that the hard-coded `email` is backed out.

Just feels wrong to me that it's hard-coded.

**Comment by jasonvarga** [comment]
Its wrong to force people to put email templates in an email subfolder in the templates folder?

**Comment by edalzell** [comment]
I guess, but couldn't you in Sender, `ensureLeft` 'email'? That why I have to do less work and you have to do more!!! ;=)

**Comment by edalzell** [comment]
Solution is to use `->in('templates')` when the email is created.

**Comment by jasonvarga** [comment]
We assume your email templates are in the `templates/email` folder. Because of convention. It's also [documented that way](https://docs.statamic.com/email#templates).

It's a bit like asking for templates to be loaded from a different spot. You put your templates in `templates` because that's how it's designed. Likewise, we've designed Statamic with the expectation that email templates go in `templates/email`.

A couple of real solutions though:

1. Use `->in('site/themes/'.Config::getThemeName().'/templates')` before `->send()`'ing the email.
2. We can add a couple of options to the templates fieldtype. Perhaps to display templates from a specific subfolder, and to save just the template name without the subfolder.

I prefer the second option.
