### ISSUE TITLE
Asset link in CP leads to "Access Denied" unless user role has access to all Asset Containers

### ISSUE THREAD

**Issue by iboxifoo** [statamic/v2-hub#1419]
### Expected behaviour
User Roles allow granular access to certain containers. If certain containers are not checked, still expect to have access to those which are.

### Actual behaviour
Unless all Asset Containers are given access, the Asset link in CP leads to an Access Denied message in the CP.

### Steps to reproduce
1.  Select not all Asset Categories under User Roles
2.  Follow Asset link in CP sidebar
3.  Access denied

### Server Details

**Operating System**:
Laravel Valet

**Web Server:**
Nginx

**PHP Version:**
7.0.17

**Statamic Version:**
2.5.8

**Updated from an older Statamic or fresh install:**
Y

**List of installed addons:**
NA

No logs generated

**Comment by mydudechris** [comment]
Experiencing a the issue with the Statamic v.2.7.2. However, I've also found that the error appears if you do not allow a collection that appears _before_ your desired collections. 

For example: 

- I have a Press role with users that have access to Press Asset collection
- I want the role to only access Press assets
- My asset collection list in the role permissions =  Event Assets, Press Assets, Blog Assets
- Unchecking Event Assets, which appears before Press Assets, triggers the Access Denied message
- Leaving Event and Press assets checked but unchecking Blog does not throw the error

It appears that the CP is looking for the first item in the list rather than the first with permissions.

**Comment by RomainFrancony** [comment]
The problem come from ```statamic/core/Http/Controllers/AssetsController.php``` in the ```index``` method, as @mydudechris pointed out, the CP is redirecting to the first container.

```php
return redirect()->route('assets.browse', $containers->first()->uuid());
```

## Fix

Update the ```index``` method

```php
$this->access('assets:*:view');

$containers = AssetContainer::all();

$currentUser = User::getCurrent();

// User is admin, no need to check
if($currentUser->isSuper()){
    return redirect()->route('assets.browse', $containers->first()->uuid());
}

// Check if the user has access to the container and redirect to the first one found
// can't use $this->access method because it will throw an exception if the user can't access to the container
foreach ($containers as $container){
    $containerUuid = $container->uuid();

    if($currentUser->can("assets:{$containerUuid}:view")){
        return redirect()->route('assets.browse', $containerUuid);
    }
}

// No container found, redirect back with error
return redirect()->back()->withErrors(translate('cp.permission_denied'));
```

@jasonvarga, @jackmcdade  could you please confirm this ?
