### ISSUE TITLE
Resolutions over 4000px wide or high breaks assets list viewer

### ISSUE THREAD

**Issue by beeldr** [statamic/v2-hub#1439]
### Actual behaviour
When I upload a file to a folder within assets with a resolution over 4000 px (not sure what the number is so i tried 5000) the folder infinitely loads on refresh. Anything over 3950 px wide gives an internal server error but it only seems to break the viewer at 4000 +  
I upgraded the memory to 128 MB but no luck so far.

### Server Details

**Operating System**:
centos 6.4

**Web Server:**
Plesk Automation 11.5

**PHP Version:**
5.5.21

**Statamic Version:**
2.5.10

**Updated from an older Statamic or fresh install:**
Original 2.5.9

**List of installed addons:**
None

### Logs
<details>
```
[2017-05-31 11:36:43] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 6012001 bytes)' in /var/www/vhosts/daytodayuitvaart.nl/httpdocs/statamic/vendor/intervention/image/src/Intervention/Image/Gd/Commands/ResizeCommand.php:56
```
</details>

**Comment by jasonvarga** [comment]
128 MB of memory should be a bear minimum. A 4000px image is a lot of work. You could try bumping it up even higher.

**Comment by jackmcdade** [comment]
Also, are you using the GD Library or ImageMagick?

**Comment by dannyuk1982** [comment]
Can this be looked at from another angle? Instead of just increasing memory and trying to deal with ever increasing sizes - can we just have a limit that can be set - filesize and/or resolution that image uploads reference, if they are over then they are just rejected & deleted with a message saying to upload something smaller?

This is the one thing that breaks statamic still as clients always do this, despite being told 100 times. They get the photos from a digital camera/phone at something like 6000px and then upload it, which breaks. It can't them be fixed without FTP/SSHing in.
