### ISSUE TITLE
FR: Logging to sentry

### ISSUE THREAD

**Issue by rrelmy** [statamic/v2-hub#1475]
There should be a logger for [Sentry](https://sentry.io/welcome/)

I built a [custom addon](https://github.com/rrelmy/statamic-sentry) for it

**Comment by efoken** [comment]
+1

**Comment by sebszocinski** [comment]
+1

**Comment by rizkysyazuli** [comment]
+1000

**Comment by torrancemiller** [comment]
+11

**Comment by jasonvarga** [comment]
Can you not use the addon remy created?

**Comment by jackmcdade** [comment]
Please do a thumbs up instead of commenting with `+X`. We can actually tally the reactions but there's no way for us to keep track of comments in a meaningful way. And just to be honest, being on the other end of a `+1` comment is demoralizing and as much as I don't want to admit it, ends up making it less likely that it will get prioritized. It shouldn't, but it's like a passive aggressive poke in the eyeball and just...does. It just does.

**Comment by torrancemiller** [comment]
Oh - sorry @jackmcdade - will keep that in mind. 

@jasonvarga - that addon looks a bit dated to me.

"USE ON YOUR OWN RISK!, this is a proof of concept." sounds like it isn't safe for production. :(

**Comment by rizkysyazuli** [comment]
@jackmcdade haha. sorry. will remember it next time.

@torrancemiller i'm currently using @rrelmy addon in production. even though the Sentry SDK it uses is a bit outdated. it works fine.

**Comment by jasonvarga** [comment]
I'm inclined to close this as you can DIY it rremy-style in v2.

In v3, it's trivial since you have control over your exception handler.
https://docs.sentry.io/platforms/php/laravel/#laravel-5x
