### ISSUE TITLE
Please make the toggle button a bit closer to it's field text OR border around the whole lot or similar

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1651]
Personally I think the toggle button is too far away from it's text IF field instructions exist. This is not such an issue when the toggle is on it's own OR if instructions aren't present but when you have multiple toggles one after the other, with instructions, it could be better.

See attached screenshot.

Thanks :)

Ant

![screen shot 2017-11-09 at 9 55 35 am](https://user-images.githubusercontent.com/5089177/32579303-7ed15db0-c534-11e7-887a-2a8550648e86.png)

**Comment by jackmcdade** [comment]
Tested in all major browsers and I don't see this issue. Maybe it's possible you have some extra markup in your instructions that's parsing the paragraph as a blockquote? If you're still having this problem, can you paste your fieldset here?

Otherwise, perhaps it's fixed now through other global style updates.

**Chrome**
![image](https://user-images.githubusercontent.com/44739/36220049-5051f004-1187-11e8-9581-1d2c9ea0635f.png)

**Safari**
![image](https://user-images.githubusercontent.com/44739/36220070-600cc690-1187-11e8-8a0c-a1b12608a6b4.png)

**Firefox**
![image](https://user-images.githubusercontent.com/44739/36220082-683a3f1e-1187-11e8-9015-3790aa751a26.png)

**Comment by anthubbard** [comment]
So, after investigation it turns out I have the 'tabs' addon installed which is indeed adding markup and messing up my toggles. I apologise. 

On another note, any chance you'd make tabs a built in feature? I have excessively long page fieldsets and breaking them into tabs is the only way to really make them useable...

Cheers,

Ant

**Comment by jackmcdade** [comment]
Yes we do plan to do that, but the way that plugin works isn't something I'm willing support. We need to address it on a higher level :)

**Comment by anthubbard** [comment]
Yeah, I wouldn't expect you to support a 3rd party script that isn't even supported anymore anyway... but would love the functionality built in to some degree.

Thanks,

Ant
