### ISSUE TITLE
Bard: Not able to delete previous line (paragraph) when using backspace preceding a fieldset

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#1738]
Statamic 2.8.2:

### Expected behaviour
Delete the previous line/paragraph with backspace.

### Actual behaviour
Kinda hard to explain! But if I for instance create a fieldset with a quote (or paragraph) under it, and add a new paragraph/item between them, I can't delete the new line with backspace from the last item. Hopefully the gif does a better job explaining!

**Bonus:** When backspacing from the start of a quote, it deletes the quote AND asks if I want to delete the fieldset (without deleting the new line). In addition clicking "Cancel" in the "Are you sure?" dialog still deletes the quote. (I know the dialog is referring to the fieldset it also is trying to delete.)

**Second bonus:** When arrowing up from the quote under the fieldset, it skips the new line and goes to the paragraph before the fieldset. I'll stop talking now, the gif will hopefully help clarify things.

Note that I'm using backspace trying to delete the new line. Lo and behold the gif:
![2018-01-20_19-30-17](https://user-images.githubusercontent.com/17156984/35186705-c52c7ea8-fe18-11e7-868e-314f6847f494.gif)

**Comment by jasonvarga** [comment]
Nice find!

However, just so you're aware, this is (mostly) intentional. We've tried to design Bard in such a way that things flow as naturally as possible with keyboard usage.

So when you hit backspace at the start of a paragraph after a set, it will treat the set like it's the previous character in the text and attempt to delete it. (The same thing will happen if you hit delete at the end of a paragraph before a set) Similarly, using the up/down arrow keys at the start/end of a text block will go past a set to the next/previous text block.

The bug you've encountered is that "being at the start of the text block" didn't take into account empty paragraphs. That has been fixed for next release.

**Comment by okse** [comment]
I expected the empty line to behave like an empty text line since it looks like a line break / new paragraph and behaves like an empty text line when putting the cursor there (and thus be included in the arrowing up) and not a set (and skipping it like it does now). Does that make sense?

**Comment by jasonvarga** [comment]
Yup makes sense. That's the part that's broken and should be fixed in the next release.

**Comment by beckysoll** [comment]
I've also been experiencing this issue, and would add one thing - if I have extra space at the end of a bard field, and i try to delete it by placing my cursor there and hitting delete, it acts as if i've hit the back button in my browser, and takes me to the previous page. The warning asking me if i really want to leave flashes for a second, but it goes back before i'm able to actually say that's what I wanted to do (which it's not).

**Comment by jasonvarga** [comment]
That's a new one I haven't heard before. Wanna open a separate issue @beckysoll ?

**Comment by beckysoll** [comment]
Sure thing, will do... wasn't sure if they were related.

**Comment by beckysoll** [comment]
Done. I discovered it's a bit more nuanced than I'd initially thought, all info here https://github.com/statamic/v2-hub/issues/1743
