### ISSUE TITLE
Taxonomy Feedback for v3

### ISSUE THREAD

**Issue by jasonvarga** [statamic/v2-hub#1776]
Hi everyone!

We are working on some architecture updates in v3, and wanted to get some feedback before we get too far into anything specific.

### The feedback we want

We want to know:

- what you like or dislike about taxonomies in v2
- what have you wanted or needed to do with them but you couldn't
- how have you used taxonomies in ways other than super basic tagging
- what other platforms do it well, and why?
- if you tag an entry in one locale/site, should it exist in the others?
- really just anything else that you think could be helpful!

Thanks!

**Comment by FR6** [comment]
I think we should be able to order the tags the way we are able to order Entries.

**Comment by jackmcdade** [comment]
@FR6 in what way?

**Comment by FR6** [comment]
@jackmcdade : we are able to order entries from a Collection:

![image](https://user-images.githubusercontent.com/286685/36113728-cafaffc2-0ffb-11e8-99da-136718fbedd9.png)

not taxonomies:

![image](https://user-images.githubusercontent.com/286685/36113790-042e283c-0ffc-11e8-86e5-4a31164ba59c.png)

**Comment by subpixelch** [comment]
Multilevel Taxonomies!

**Comment by FrittenKeeZ** [comment]
This is more general than just taxonomies, but a way to customize slugging based on locale.
Fx. Danish slugs some characters differently than English, namely Ø and Å - rendering `kødpålæg` as `koedpaalaeg` and not `kodpalaeg` as now.

**Comment by jackmcdade** [comment]
@FrittenKeeZ can you open that as a separate issue? It will definitely get lost here.

**Comment by codyspring** [comment]
I second @subpixelch's multi-level taxonomies. We have a large auto dealer website and it would be nice to use taxonomies for make, model, trim, etc and build URLs around that.

**Comment by FrittenKeeZ** [comment]
@jackmcdade sure thing, the new issue is here #1778.

**Comment by peimn** [comment]
Is there any plan to support relational or non-relational databases?

**Comment by jackmcdade** [comment]
@peimn that is unrelated to this issue.

**Comment by peimn** [comment]
I think it would be better optimized to use taxonomies with a database. Don't you?

**Comment by jackmcdade** [comment]
Not anymore than anything else.

**Comment by beckysoll** [comment]
_what you like or dislike about taxonomies in v2_

I don't know if i'm alone in this but I constantly struggle with choosing whether something should be a taxonomy or a collection. Some things are obvious (eg blog posts in a collection and tags in a taxonomy), but some things are not. Let's say you have teams of people... people would be a collection for sure. If the team has its own page and some content, should that be a taxonomy or a collection? I've encountered a lot of dilemmas like this ( I could find more specific examples if that would be helpful). 

I have often found myself wishing they were 1 combined thing that had the superpowers of both. Maybe it's just because they are both so flexible? At the very least, looking at the way they work in v2, I would love to see more information about why you'd choose one over the other. Examples, technical reasons why 1 is ideal for certain situations, etc. etc. Something I could reference every time my brain starts hurting.

_what have you wanted or needed to do with them but you couldn't_

It's been said many times by many people but... **ordering** and **nesting**

_what other platforms do it well, and why?_

FWIW, I think you guys do it best, as per usual.

**Comment by gmcz** [comment]
>     what you like or dislike about taxonomies in v2

I like how flexible they are. It's what makes them hard to understand, but it's what makes them powerful.

>     what have you wanted or needed to do with them but you couldn't

Hierarchy within them is something I've wanted before. Genus and species. The ability to create "nested tags" or "nested categories". 

>     how have you used taxonomies in ways other than super basic tagging

I can't think of a use that isn't essentially "tagging"... but I've used them as _advanced_ tagging, I suppose. Basically, the ability to add a whole fieldset to a "tag" is great. It opens a lot of possibilities that a simple array of "tags" in yaml doesn't so easily do.

>     what other platforms do it well, and why?

Dunno.

>     if you tag an entry in one locale/site, should it exist in the others?

Sometimes! I've not messed with this yet, but I think what I'd want is the _option_ to make a taxonomy "localizable", and if it is then I'd want them in sync. If it's not localizeable then no. 

>     really just anything else that you think could be helpful!

I think that the terminology and description of them may be the biggest challenge for folks. Right now all the examples I remember in the docs and the "flatness" of them really encourage "tagged" thinking.  I think at least 80% of the battle will be naming them, writing copy for the CP UI, and explaining in the docs.

**Comment by jackmcdade** [comment]
Thanks for feedback everyone. Will be factored in w/ v3.
