### ISSUE TITLE
FR-modification of .htaccess

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#1863]
Please consider adding this to the sample .htaccess file. Just leave it commented out.  It shows people how to redirect to www and https which they probably should do anyway… Just replace domain.com with your domain and uncomment the lines.
```
RewriteEngine On
# RewriteBase /

# ------------------------------------------------------------------------------
# REDIRECT TO WWW AND HTTPS
# ------------------------------------------------------------------------------

# <IfModule mod_rewrite.c>
#   # Force website to use "www and https"
#   RewriteCond %{HTTPS} off [OR]
#   RewriteCond %{HTTP_HOST} !^www\.domain\.com$ [NC]
#   RewriteRule ^(.*)$ https://www.domain.com/$1 [L,R=301]
# </IfModule>

# ------------------------------------------------------------------------------
# REMOVE TRAILING SLASHES
# ------------------------------------------------------------------------------
```

**Comment by jackmcdade** [comment]
Will be in next release. Took a different approach though and split up www/no-www and https as all separate.

**Comment by bgarrant** [comment]
Sounds great Jack. Mine is not best code I am sure. Can you send me the snippet and I will add it to the three sites .htaccess files I have so far?

Bryan Garrant
Garrant Consulting LLC
518-327-5159

**Comment by jackmcdade** [comment]
https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess?ts=2#L280-L408


On March 31, 2018 at 11:20:49 AM, bgarrant (notifications@github.com) wrote:

Sounds great Jack. Mine is not best code I am sure. Can you send me the
snippet and I will add it to the three sites .htaccess files I have so far?

Bryan Garrant
Garrant Consulting LLC
518-327-5159

> On Mar 31, 2018, at 9:29 AM, Jack McDade <notifications@github.com> wrote:
>
> Will be in next release. Took a different approach though and split up
www/no-www and https as all separate.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/statamic/v2-hub","title":"statamic/v2-hub","subtitle":"GitHub
repository","main_image_url":"
https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png
","avatar_image_url":"
https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
in GitHub","url":"https://github.com/statamic/v2-hub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jackmcdade
in #1863: Will be in next release. Took a different approach though and
split up www/no-www and https as all separate."}],"action":{"name":"View
Issue","url":"
https://github.com/statamic/v2-hub/issues/1863#issuecomment-377693113"}}}

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/statamic/v2-hub/issues/1863#issuecomment-377700384>,
or mute
the thread

**Comment by bgarrant** [comment]
Thanks Jack
