### ISSUE TITLE
group_by_date doesn't like from="{{ variable }}"

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#1905]
When you have a few similar collections, it's super handy to use the same template and the current pages mounted collection:

`{{ collection from="{{ mount }}" }}`

But, if you want to group those entries, there's no output from the tag:

`{{ collection group_by_date="M Y" as="entries" from="{{ mount }}" }}`

An embedded variable give no dice as well.

However, this works:

`{{ collection group_by_date="M Y" as="entries" from="event" }}`

**Comment by jasonvarga** [comment]
Interesting, it seems like the order of the parameters affects things.

Regardless, you shouldn't be using double braces at all inside parameters. They should be single ones.

Even better, we introduced the colon prefix that would evaluate the parameters so you don't need braces at all:

```
{{ collection :from="mount" }}
```

By using the colon, it will get the value of `mount` rather than the literal string "mount".
