### ISSUE TITLE
Multiple "title" fields now breaks CP views.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/v2-hub#1973]
**Describe the bug**
I'm not sure if this was ever supposed to work but it is now a breaking change. A title field at the top of a fieldset when combined with a title field elsewhere (in my case, a bard set) causes the CP to error on the specific fieldset edit page as well as editing a page using that fieldset.

Editing the fieldset
<img width="330" alt="screen shot 2018-05-27 at 00 43 25" src="https://user-images.githubusercontent.com/622598/40587130-cbde92fa-6190-11e8-88ff-0535c6ab4613.png">

Trying to edit the page
<img width="1393" alt="screen shot 2018-05-27 at 00 45 12" src="https://user-images.githubusercontent.com/622598/40587132-d0ae997e-6190-11e8-82ea-de0e64ef9c7a.png">

Sample page
<img width="344" alt="screen shot 2018-05-27 at 09 33 34" src="https://user-images.githubusercontent.com/622598/40587159-0f5bd38a-6191-11e8-88a9-edd7747bbbbf.png">
Note: changing from title to name fixes the bug.

**Expected behavior**
Editing and creating works as before the 2.9+ upgrade.

**Screenshots**

**Environment details (please complete the following information):**
 - Statamic Version 2.9.4
 - Fresh Install or Upgrade: Upgrade
 - OS: Valet and forge production
 - Browser: chrome, safari, etc
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: Akismet

**Comment by jasonvarga** [comment]
The issue is that the title _fieldtype_ has been removed.

The updater should have adjusted your fieldset automatically. If not, you could run `php please update:housekeeping` to manually trigger it.

All it really did was change `type: title` to `type: text`.

If you were using `type: title` anywhere other than the top level (eg. inside Bard or Replicator fields) they wouldn't be converted. `type: title` wasn't really intended to be used anywhere else.

Just change `type: title` to `type: text` and you should be good to go.

**Comment by jasonvarga** [comment]
Just to confirm, you can name your field `title` within Bard, just not give it a `type` of `title`.
