### ISSUE TITLE
Taxonomy must have a page or entry assigned to show

### ISSUE THREAD

**Issue by TomS-** [statamic/v2-hub#1975]
**Describe the bug**
Even though the default min_count is 0, a page or entry must be assigned to the taxonomy for it to show. Manually setting the min_count to 0 doesn't cause the taxonomy to show.

**To Reproduce**
1. Create a taxonomy
2. Output taxonomies to the screen with {{ taxonomy:category }}
3. Taxonomies without a page/entry assigned will not show regardless of min_count

**Expected behavior**
Taxonomy entries should show regardless of min_count.

**Environment details (please complete the following information):**
 - Statamic Version 2.9.4

**Comment by TomS-** [comment]
Hi @jasonvarga show="all" works. However, is this correct functionality? The taxonomies are published. Seems like min_count should control weather it should be shown regarding the page count?

**Comment by jasonvarga** [comment]
Yeah, pretty much.
This tag filters the _underlying content_ - eg. the entries that use the terms, not the terms themselves.
So yes you can set min count, but when it filters by the rest of the default parameters (eg. show_unpublished) since it filters based on the entries, and there isn't one, the term will be removed.
