### ISSUE TITLE
new page with custom template generates fieldset parameter instead of template

### ISSUE THREAD

**Issue by alexmilde** [statamic/v2-hub#2132]
**Describe the bug**
Create new page with custom page template. fieldset is set in markdown but template is not

**To Reproduce**
1. Go to 'pages -> create page'
2. Choose custom page type
3. Check folder pages/PAGENEME/index.md
4. See mssing template parameter

**Comment by jackmcdade** [comment]
That's how it's supposed to work. The picker chooses the fieldset, and the template can be defined by it.

**Comment by alexmilde** [comment]
like i said. if i choose the page type the selected template will not be written in the .md file.

**Comment by jackmcdade** [comment]
You're not selecting a template, you're selecting a fieldset. If it has a template field (e.g. with a default), when you save that content, voila. Template is set.

**Comment by alexmilde** [comment]
ok i try to explain again.
out of the box install:
gallery seems to use its own template "gallery"
if you go through the fresh install and create a new page with page type gallery. the template "gallery" will not be written inside the markdown file.

**Comment by jackmcdade** [comment]
Fair enough, though not a bug, we just hardcoded it in the file because it's just a demo site not really meant to be reused.

**Comment by alexmilde** [comment]
awesome work btw. the company i work for might buy a license ;) still evaluating though.

**Comment by jackmcdade** [comment]
Fair enough!


On August 22, 2018 at 1:33:22 PM, Alex Milde (notifications@github.com)
wrote:

awesome work btw. the company i work for might buy a license ;) still
evaluating though.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/statamic/v2-hub/issues/2132#issuecomment-415114568>,
or mute
the thread
