### ISSUE TITLE
Bard shouldn't be opinionistic about heading font weight

### ISSUE THREAD

**Issue by pxwee5** [statamic/v2-hub#2380]
**Describe the bug**
When adding H1 to H6 styles to text, it bolds it by default.

**Expected behavior**
Should not bold font by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/14123790/55760413-213e8480-5ab0-11e9-9629-f062f72520fc.png)

**Comment by jackmcdade** [comment]
Unfortunately there's not a lot we can do about this. That bold comes from `ContentEditable`, which is interpreting it from the CP's stylesheet. If we don't make the headings bold here, the whole typographical flow of Bard's content is pretty lackluster. If I remember correctly, it doesn't actually write a `<b>` tag in or anything, so it's just kind of an annoying thing.

Also, it's [not an issue in v3](https://v3.statamic.com/blog/bard-reimagined-again) so it will go away. Since there isn't much I can do in v2 and we have a fix in v3, I'm going to close this issue. Thanks for the report!
