### ISSUE TITLE
Ability to import a CSV

### ISSUE THREAD

**Issue by andregoldstein** [statamic/v2-hub#397]
I know this isn't simple as it will have to match columns to fields etc but I'd love this to be part of core or a provided addon. I'm guessing most software can export to CSV so may be the best format for importing data.

I've got an old site with a hundred or so signed up users, would be great to be able to port these over.

**Comment by seantubridy** [comment]
Yes please! This is one of the only things keeping me from moving platforms for some sites. I don't want to manually recreate hundreds of entries.

**Comment by jasonvarga** [comment]
https://docs.statamic.com/importer#creating-your-own-exporter

**Comment by eimpacteric** [comment]
I was coming to suggest a CSV importer, and noticed this feature request was closed...but there still isn't a CSV importer. Am I missing something? or you just don't have plans to create a CSV importer?

**Comment by jasonvarga** [comment]
Instead of generating a CSV, you should generate a file according to our importer spec.

**Comment by eimpacteric** [comment]
The potential use of CSVs is really broad and very easy to create and edit from a user's perspective. A database table can be easily exported as a CSV and spreadsheets can easily be exported as CSV. Working with website info in a spreadsheet really comes in handy sometimes. Since CSVs are such a common and easily producible file format (and I'd guess is way more used by the "average" user than JSON), I'd still suggest it as an appreciated way to import data. Totally up to you...just saying...

Thanks Jason!

**Comment by jasonvarga** [comment]
Since CSVs can come in any shape or size, we'd have to build something to customize the input. Map columns to fields, in collections, terms, pages, etc.

If your application requires it to constantly be updated from another system, perhaps an addon to bring the data in would be more appropriate.
