### ISSUE TITLE
Friendly suggestion wrt image compression...

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-hub#468]
Just for grins, I took the `/assets/img` folder from B17 and fed the files therein one at a time into my favorite online image compression utility: [https://compressor.io](https://compressor.io). The results were pretty impressive:

```
Comparison vs https://compressor.io/compress
  before      after    saves filename
---------------------------------------------------------
  130.75K  >   97.95K  25%   black-bear-cubs.jpg
   66.36K  >   52.11K  21%   coffee-mug.jpg
  196.27K  >  150.91K  23%   jedi-set.jpg
   72.80K  >   57.87K  21%   me.jpg
  406.81K  >  308.81K  24%   redwood-balance.jpg
  717.88K  >  200.00K  72%   redwood-james-irvine-trail.jpg
  706.79K  >  211.47K  70%   redwood-north-ridge-trail.jpg
  231.70K  >  171.67K  26%   redwood-sign.jpg
  673.65K  >  255.20K  62%   redwood-snow.jpg
  772.13K  >  224.48K  71%   redwood-sunrise.jpg
   69.16K  >   53.18K  23%   roosevelt-elk.jpg
   84.34K  >   67.48K  20%   stetson.jpg
---------------------------------------------------------
 4128.64K  > 1851.13K  45%   TOTAL
```

I don't know what [https://compressor.io/compress](https://compressor.io/compress) is doing, but I sure wish it was built into Statamic!

In any case, How about using compressor.io’s squished versions of those images for all future releases? ’Cause like they say, *“Schmalla ist bettah!”* ;-)

**Comment by jackmcdade** [comment]
Not really something we can bake in with wide support. Closing this one down.

**Comment by iDGS** [comment]
For kicks, I just revisited the KB savings you'd get for compressing the images in the default download (v2.8.1/assets/img) using https://compressor.io/compress, and it still seems worthwhile. Here's the results:

![sqz-redwood-savings-compressor](https://user-images.githubusercontent.com/1248937/35000711-193fbcbc-fab3-11e7-9cf7-9a473f45f2e2.jpeg)

(JOBTW, the savings for compressing the above image snippet from Excel were 170.14KB —> 80.55KB (saved 53%))

So, I understand about can't fold it into the product. OK. But why not lighten everyone's new version / update download burden by about 2 MB a pop? (…For those of us who like getting the full package instead of or in addition to just using the yes-I-love-it Updater thingie in the CP)

**Comment by jackmcdade** [comment]
But what’s the difference after zipping though?


On January 16, 2018 at 12:04:32 PM, David G. Smith (notifications@github.com)
wrote:

For kicks, I just revisited the KB savings you'd get for compressing the
images in the default download (v2.8.1/assets/img) using
https://compressor.io/compress, and it still seems worthwhile. Here's the
results:

[image: sqz-redwood-savings-compressor]
<https://user-images.githubusercontent.com/1248937/35000711-193fbcbc-fab3-11e7-9cf7-9a473f45f2e2.jpeg>

(JOBTW, the savings for compressing the above image snippet from Excel were
170.14KB —> 80.55KB (saved 53%))

So, I understand about can't fold it into the product. OK. But why not
lighten everyone's new version / update download burden by about 2 MB a
pop? (…For those of us who like getting the full package instead of or in
addition to just using the yes-I-love-it Updater thingie in the CP)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/statamic/v2-hub/issues/468#issuecomment-358031600>, or mute
the thread

**Comment by iDGS** [comment]
🤷‍♂️ You got me there! LOL (I dunno) NVM if if makes no diff.

**Comment by iDGS** [comment]
Ya, so, in the interest of Science, I unzipped 2.8.1, replaced that assets/img folder with one just like it, except with all the aforementioned compressed images (renamed to be identical to the originals), and re-zipped the whole Statamic folder using the Mac's compress folder command. 

Result? 

It was BIGGER than the original!

(Below: originals on left, "improvements" on right)

![comparefoldersizes-compressor](https://user-images.githubusercontent.com/1248937/35003494-06a6f414-fabb-11e7-8b59-e23d09c3b542.jpeg)

![comparezipsizes-compressor](https://user-images.githubusercontent.com/1248937/35003503-0d7cddd0-fabb-11e7-853b-e1f9fe9c1aba.jpeg)

🤕 🤦‍♂️ (Hoping you get a chuckle or two from my "learning experience.)

**Comment by iDGS** [comment]
I can add that the un-zip of the re-zip of the re-do DID give me back the same, smaller sized images in assets/img, so…

🤔 

Makes me wonder about which is more important to optimize (as a general principle): the bundle, or the performance of the un-bundled images once they're unzipped and running on a server accessible to the public. :inspects horse; finds it dead; gives it one final nudge and wanders off…:
