### ISSUE TITLE
Some words didn't get translated in CP

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#585]
### Steps to reproduce
1. I tried to localize by following steps in docs
2. Created TR localization files in statamic/resources/lang/tr

### Actual behaviour
Some words didn't get translated in CP
![_filepane-screen shot 2016-04-06 at 2 25 13 pm](https://cloud.githubusercontent.com/assets/5695187/14312894/a38159b8-fc03-11e5-87cb-02339999780a.png)

### Server configuration
**Operating system**: El Capitan 10.11.3

**Web server:** NGINX

**PHP version:** 5.6.9

**Statamic version:** 2

**Updated from an older Statamic or fresh install:** Fresh install

**Comment by jasonvarga** [comment]
Someone beat you to it. Check out #293

**Comment by ebeauchamps** [comment]
Jason, peimm:

Just a thought on this. when I started translating the CP back in the ol'days of Beta8, I remember I add some trouble with some strings, but not all, that where translated in my `fr` folder but weren't fetch in the CP so I was getting exactly the same behavior as peimm.

In fact, in order to get all the translated strings, I add to rename my folder to `en` !

As of today, this still is what I am doing.

As you know, you cannot put your own language in FIRST in the system settings. English must be the first language. And I guess some translated strings aren't found when there are both an `en` and a `fr` or `tr` folder in the `lang` folder.

I can check again for this tonight If you wish

**Comment by ebeauchamps** [comment]
OK, so I did reproduce the same behavior as @peimn  

Therefore, I get a mix of translated and English strings in the CP though those English strings are included in my own cp.php file with their translation in my language.

**Comment by peimn** [comment]
I think it is not acceptable to forcing users to default locale!

In statamic/core/CP/Navigation/NavFactory.php I added one more $slug parameter to item()
and am using item() this way: $nav = $this->item(trans('cp.content'), 'content');
also added slug method to NavItem class

now in statamic/resources/views/partials/nav-main-items.blade.php changed class nav-{{$item->name() to nav-{{$item->slug()

That's it! nav now is localized

This is just a 5 minutes solution..
There might be better ways to localize other parts too

Thanks a lot

**Comment by jackmcdade** [comment]
We agree! We're not forcing users, there's just a few things we missed when localizing. Updates coming soon :)

**Comment by peimn** [comment]
For navigation just did this:

`$nav = $this->item('content')->title(trans('cp.content'));`

in _/core/CP/Navigation/NavFactory.php_

**Comment by peimn** [comment]
Other parts are also get translated just by changing site_locale() to 'en' in path: 'statamic/core/Http/ViewComposers/TranslationComposer.php'

I think it just need a change in JS function that fetches translations.

<img width="1076" alt="screen shot 2016-04-14 at 12 35 42 am" src="https://cloud.githubusercontent.com/assets/5695187/14507659/ed0bc0a2-01d8-11e6-8e0b-bc6a703a330a.png">
