### ISSUE TITLE
FR: Auto-resolve slug for duplicate entries

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/v2-hub#777]
### Steps to reproduce
1. Create collection entry
2. Create another collection entry with same title (and thus slug by default)
3. Second entry overwrites first.
### Expected behaviour

Second entry auto-generates new slug and filename.
### Actual behaviour

New entry overwrites existing and loses original content.

**Comment by trevorgehman** [comment]
I would definitely like to see this. Would like to make sure there are no route conflicts in general, such as manually-specified routes.

**Comment by rrelmy** [comment]
I don't see that as feature request, this is a bug!
There should be at least an error when a new collection entry is created.

We had multiple customers overwriting their old content because of the same titles.

At first this problem is not visible because as long the cache is not cleared all the entries show up normally but disappear into one when the cache is repopulated.

**Comment by jasonvarga** [comment]
This seems like such an obvious thing and such an old issue, I feel like it must have been done at some point. It might be a regression.

**Comment by rrelmy** [comment]
I saw this issue today in version 2.1.13 and 2.1.18, I can also reproduce it in 2.5.1

**Comment by jasonvarga** [comment]
Regardless, we'll get it done. Thanks for the report.
