### ISSUE TITLE
Treat env vars in addon settings the same as in core settings

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#846]
### Steps to reproduce
1. Set addon settings in env vars.
2. Visit addon settings page in CP.
### Expected behaviour

I expected to see:

> Managed externally by your environment.
### Actual behaviour

I saw the parsed values of the environment variables.

**Comment by jcohlmeyer** [comment]
I also see this issue in my addon. Also saving the settings changes the settings in the addon folder, not the enviroment file. Very confusing for the user as it looks like nothing happened.

**Comment by edalzell** [comment]
Similar to #1073?

**Comment by curtisblackwell** [comment]
@jcohlmeyer it shouldn't change the settings in `.env`. That has to be done directly in the file.

**Comment by jcohlmeyer** [comment]
Yes @edalzell it is similar to #1073 I think it is actually closer to what I mean.

The settings are saved in the addon's setting file even though they are overridden by the environment settings file. Changing the settings in the CP saves the settings to the addon's settings file, which is confusing because you do not see those changes in CP. You should not be able to edit these values at all when they are controlled by the environment settings file as per your point @curtisblackwell
