### ISSUE TITLE
mkdir(): Invalid argument

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#905]
### Server configuration
**Operating system**: Win7

**Web server:** XAMPP

**PHP version:** 7

**Statamic version:** 2.1.5

**Updated from an older Statamic or fresh install:** Fresh

![screenshot_11](https://cloud.githubusercontent.com/assets/5695187/18025317/6eda771e-6c3b-11e6-9d9c-7ffd7e637769.png)

**Comment by edalzell** [comment]
this is usually permissions problem @peimn, have you made `local`, `site`, `statamic` 777 recursively?

**Comment by peimn** [comment]
I had not this error on 2.1.3. Also tried to change permissions but the error persists.

**Comment by jackmcdade** [comment]
Are you 100% sure you set the permissions too 777 RECURSIVELY?

**Comment by peimn** [comment]
I did everything about permissions. Nothing changed.

**Comment by peimn** [comment]
I can install 2.1.3 but 2.1.5 not works

**Comment by ianhubbard** [comment]
From looking at that image you have something funky going on with your directory references.
`D:\xampp\statamic/D:\xampp\statamic\statamic` cannot be right. I'm guessing the Invalid argument is due to the second colon in the filename. the question why you have the path prefix twice is probably a bug, or you've set something wrong in the settings.

What are the settings under `filesystems:` in `site/settings/system.yaml`?

**Comment by jasonvarga** [comment]
It's a windows issue. Someone else reported the same thing. We'll get it sorted out for next release.

**Comment by jasonvarga** [comment]
Fixed for next release.
